# Generated by Django 3.1.6 on 2021-02-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('timestamp', models.DateField(blank=True)),
            ],
        ),
    ]
